package com.limelight.binding.input.touch;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;

/** Runtime settings for mouse input generated by uncovered stream areas. */
public final class BlankAreaInputSettings {
    public static final int MIN_SENSITIVITY_PERCENT = 25;
    public static final int MAX_SENSITIVITY_PERCENT = 300;

    // Retained as a migration source for LumaPad v0.8's single sensitivity setting.
    private static final String LEGACY_SENSITIVITY_KEY =
            "seekbar_osc_background_mouse_sensitivity";
    private static final String ACTIVE_SENSITIVITY_KEY =
            "runtime_blank_area_mouse_sensitivity";
    private static final String ACTIVE_LEFT_CLICK_KEY =
            "runtime_blank_area_left_click";

    public static final class State {
        public final float sensitivity;
        public final boolean allowLeftClick;

        private State(float sensitivity, boolean allowLeftClick) {
            this.sensitivity = sensitivity;
            this.allowLeftClick = allowLeftClick;
        }
    }

    private BlankAreaInputSettings() {
    }

    public static int getLegacySensitivityPercent(Context context) {
        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(context);
        return clampSensitivity(preferences.getInt(LEGACY_SENSITIVITY_KEY, 100));
    }

    public static State readActive(Context context) {
        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(context);
        int sensitivity = clampSensitivity(preferences.getInt(ACTIVE_SENSITIVITY_KEY,
                getLegacySensitivityPercent(context)));
        return new State(sensitivity / 100f,
                preferences.getBoolean(ACTIVE_LEFT_CLICK_KEY, true));
    }

    public static void apply(Context context, int sensitivityPercent, boolean allowLeftClick) {
        PreferenceManager.getDefaultSharedPreferences(context).edit()
                .putInt(ACTIVE_SENSITIVITY_KEY, clampSensitivity(sensitivityPercent))
                .putBoolean(ACTIVE_LEFT_CLICK_KEY, allowLeftClick)
                .apply();
    }

    public static int clampSensitivity(int sensitivityPercent) {
        return Math.max(MIN_SENSITIVITY_PERCENT,
                Math.min(MAX_SENSITIVITY_PERCENT, sensitivityPercent));
    }
}
